import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const data = JSON.parse(await readFile(path.join(root, 'data/site.json'), 'utf8'));
const p = data.profile;
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const external = (url, label, cls = '') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label}<span class="external-mark" aria-hidden="true">↗</span></a>`;
const tags = values => `<div class="tags">${values.map(t => `<span>${esc(t)}</span>`).join('')}</div>`;
const byId = id => data.publications.find(pub => pub.id === id);
const publications = [...data.publications].sort((a,b) => b.year-a.year || (a.id==='paper-14' ? -1 : b.id==='paper-14' ? 1 : a.title.localeCompare(b.title,'en')));
const authorHtml = pub => pub.authors.map(name => name === p.name ? `<strong>${esc(name)}</strong>` : esc(name)).join(', ');
const venueLine = pub => `${esc(pub.venue)}${pub.volume ? `, ${esc(pub.volume)}${pub.issue ? `(${esc(pub.issue)})` : ''}` : ''}${pub.pages ? `, pp. ${esc(pub.pages).replaceAll('-','–')}` : ''}${pub.articleNumber && !pub.pages ? `, Article ${esc(pub.articleNumber)}` : ''}, ${pub.year}`;
function bibtex(pub) {
  const fields = { title:`{${pub.title}}`, author:pub.authors.map(n => { const parts=n.split(' '); const last=parts.pop(); return `${last}, ${parts.join(' ')}`; }).join(' and '), [pub.type==='Journal'?'journal':'booktitle']:pub.venue, year:pub.year, volume:pub.volume, number:pub.issue, pages:pub.pages?.replaceAll('-','--'), eid:pub.articleNumber, doi:pub.doi, url:`https://doi.org/${pub.doi}` };
  return `@${pub.type==='Journal'?'article':'inproceedings'}{zeng${pub.year}${pub.id.replace('paper-','')},\n${Object.entries(fields).filter(([,v])=>v).map(([k,v])=>`  ${k} = {${v}}`).join(',\n')}\n}`;
}
const navigation = [ ['about','About'], ['research','Research'], ['publications','Publications'], ['highlights','Highlights'], ['cv','CV'], ['interests','Interests'], ['contact','Contact'] ];
function head(title, route, description, extra='') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="author" content="${esc(p.name)}"><meta name="theme-color" content="#2E6E9E"><link rel="canonical" href="${p.siteUrl}${route}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${p.siteUrl}${route}"><meta property="og:image" content="${p.siteUrl}/assets/images/social-mountains.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/images/qingkui-avatar.jpg" type="image/jpeg"><link rel="stylesheet" href="/assets/css/styles.css"><script src="/assets/js/app.js" defer></script>${extra}</head>`;
}
function header(home = true) {
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="scroll-progress" aria-hidden="true"></div><div class="container nav-row"><a class="brand" href="${home?'#home':'/'}" aria-label="Qingkui Zeng homepage"><span class="brand-initials">QZ</span><span class="brand-name">Qingkui Zeng</span></a><button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="primary-nav" hidden>Menu</button><nav id="primary-nav" aria-label="Primary navigation">${navigation.map(([id,label])=>`<a href="${home?'':'/'}#${id}">${label}</a>`).join('')}</nav></div></header>`;
}
function footer() {
  return `<footer class="site-footer"><div class="container footer-row"><p>© ${data.updated.slice(0,4)} ${p.name}<span class="footer-dot">·</span>Updated ${data.updated}</p><a href="#home">Back to top <span aria-hidden="true">↑</span></a></div></footer><div class="toast" role="status" aria-live="polite" hidden></div>`;
}
const intro = `<p>I am a Lecturer in the School of Artificial Intelligence at Tongling University. My research focuses on privacy protection and federated learning: how to learn from distributed data while protecting individuals and keeping collaborative systems reliable.</p><p>I received my Ph.D. in Information and Communication Engineering from Nanjing University of Information Science and Technology in June 2025, and joined Tongling University in July 2025.</p><p>My work spans local differential privacy, poisoning defenses, efficient learning for connected devices, and the security of language model applications.</p>`;
function career(kind) {
  return `<article class="career-card"><p class="eyebrow">${kind==='education'?'01 / EDUCATION':'02 / EMPLOYMENT'}</p>${data[kind].map(item=>`<div class="career-entry"><p class="date">${esc(item.dates)}</p><h3>${esc(item.degree || item.role)}</h3><p>${esc(item.institution)}</p>${item.school?`<p class="muted">${esc(item.school)}</p>`:''}</div>`).join('')}</article>`;
}
function publication(pub, cv=false) {
  if(cv) return `<li><h3>${esc(pub.title)}</h3><p>${authorHtml(pub)}</p><p>${venueLine(pub)}</p><a href="https://doi.org/${esc(pub.doi)}">doi:${esc(pub.doi)}</a>${pub.yearNote?`<p class="year-note">${esc(pub.yearNote)}</p>`:''}</li>`;
  const search = [pub.title,...pub.authors,pub.venue,pub.venueShort,...pub.keywords].join(' ');
  return `<article class="publication-card" id="${pub.id}" data-year="${pub.year}" data-search="${esc(search)}"><div class="publication-top"><div class="badges"><span class="badge venue-badge">${esc(pub.venueShort)}</span><span class="badge">${pub.type}</span>${pub.authors[0]===p.name?'<span class="badge author-badge">First author</span>':''}</div><span class="publication-year">${pub.year}</span></div><h3>${esc(pub.title)}</h3><p class="authors">${authorHtml(pub)}</p><p class="venue">${venueLine(pub)}</p>${pub.yearNote?`<p class="year-note">${esc(pub.yearNote)}</p>`:''}<div class="publication-bottom">${tags(pub.keywords)}<div class="publication-links">${external(`https://doi.org/${pub.doi}`,'Paper')}${pub.preprintUrl?external(pub.preprintUrl,'Preprint'):''}<button type="button" class="bibtex-button" hidden aria-label="Copy BibTeX for ${esc(pub.title)}" data-bibtex-id="${pub.id}">BibTeX</button></div></div><details class="citation-details"><summary>View citation</summary><pre tabindex="0" id="bib-${pub.id}">${esc(bibtex(pub))}</pre></details></article>`;
}
const years = [...new Set(publications.map(pub=>pub.year))];
const schema = { '@context':'https://schema.org', '@type':'Person', name:p.name, url:p.siteUrl, jobTitle:p.role, worksFor:{'@type':'CollegeOrUniversity',name:p.institution}, alumniOf:{'@type':'CollegeOrUniversity',name:data.education[0].institution}, sameAs:[p.scholarUrl,p.githubUrl], knowsAbout:['Privacy protection','Federated learning'] };
const homepage = `${head(`${p.name} | Privacy & Federated Learning`,'/','Qingkui Zeng, Lecturer at Tongling University. Research in privacy protection, federated learning and secure learning systems.',`<link rel="preload" as="image" href="/assets/images/snow-mountains.webp"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<','\\u003c')}</script>`)}<body id="home">${header()}<main id="main">
<section class="hero" aria-labelledby="hero-title"><img class="hero-landscape" src="/assets/images/snow-mountains.webp" alt="" width="1774" height="887" fetchpriority="high"><div class="hero-overlay"></div><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">LECTURER · TONGLING UNIVERSITY</p><h1 id="hero-title">Qingkui<br>Zeng<span class="name-period">.</span></h1><p class="hero-statement">Learning together.<br><span>Keeping data private.</span></p><p class="hero-description">I study privacy protection and federated learning, with an interest in reliable, efficient and secure learning systems.</p><div class="hero-actions"><a class="button primary" href="#publications">View Publications <span aria-hidden="true">↗</span></a><a class="button secondary" href="mailto:${p.primaryEmail}">Email Me</a></div><div class="quick-facts"><div><strong>Research</strong><span>Privacy & federated learning</span></div><div><strong>Based in</strong><span>${p.location}</span></div></div></div><aside class="profile-card" aria-label="Academic profile"><div class="profile-top"><img class="avatar" src="/assets/images/qingkui-avatar.jpg" alt="Qingkui Zeng's guitar profile photograph" width="140" height="140"><span class="profile-label">ACADEMIC PROFILE</span></div><h2>${p.name}</h2><p class="profile-role">${p.role}</p><p>${p.school}<br>${p.institution}</p><div class="profile-divider"></div><p class="profile-focus">Privacy protection.<br>Collaborative learning.<br>Dependable systems.</p><div class="profile-links">${external(p.scholarUrl,'Google Scholar')}${external(p.githubUrl,'GitHub')}</div><a class="profile-email" href="mailto:${p.primaryEmail}">${p.primaryEmail}</a></aside></div><div class="container hero-bottom"><span>RESEARCH · CURIOSITY · EXPLORATION</span><a href="#about">Discover more <span aria-hidden="true">↓</span></a></div></section>
<section id="about" class="section" aria-labelledby="about-title"><div class="container"><div class="split-heading"><div><p class="eyebrow">ABOUT</p><h2 id="about-title">Useful learning.<br> Thoughtful privacy.</h2></div><div class="prose">${intro}<div class="inline-links">${external(p.scholarUrl,'Google Scholar')}<a href="/cv/">View my CV <span aria-hidden="true">↗</span></a></div></div></div><div class="stats-grid" aria-label="Academic statistics">${[[data.metrics.publications,'Publications'],[data.metrics.citations,'Citations'],[data.metrics.hIndex,'h-index'],[data.metrics.i10Index,'i10-index']].map(([value,label])=>`<article><strong>${value}</strong><span>${label}</span></article>`).join('')}</div><p class="snapshot-note">Google Scholar snapshot · 5 October 2026. ${external(p.scholarUrl,'See current metrics')}</p></div></section>
<section id="research" class="section tint" aria-labelledby="research-title"><div class="container"><div class="section-heading"><div><p class="eyebrow">RESEARCH</p><h2 id="research-title">Questions that connect my work.</h2></div><p>Privacy, robustness and efficiency<br>across collaborative learning systems.</p></div><div class="research-grid">${data.research.map((item,i)=>`<article class="research-card"><span class="card-index">0${i+1}</span><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p>${tags(item.tags)}</article>`).join('')}</div></div></section>
<section id="news" class="section" aria-labelledby="news-title"><div class="container news-grid"><div><p class="eyebrow">NEWS</p><h2 id="news-title">Recent updates.</h2><p class="section-description">Publications and academic milestones.</p></div><div class="news-list">${data.news.map((item,i)=>`<article class="news-item ${i===0?'featured':''}"><time>${esc(item.date)}</time><div><span class="news-category">${esc(item.category)}</span><p>${esc(item.text)}${item.paper?` <a href="#${item.paper}" aria-label="View publication mentioned in ${item.date}">View paper <span aria-hidden="true">↗</span></a>`:''}</p></div></article>`).join('')}</div></div></section>
<section id="publications" class="section tint" aria-labelledby="publications-title"><div class="container"><div class="section-heading"><div><p class="eyebrow">PUBLICATIONS</p><h2 id="publications-title">Work in print.</h2></div>${external(p.scholarUrl,'Full Scholar profile','text-link')}</div><p class="publication-intro">Journal and conference papers. Years follow the publisher’s final citation; earlier records and conference years are noted where they differ.</p><div class="publication-controls" hidden><div class="search-field"><label for="publication-search">Search publications</label><input id="publication-search" type="search" placeholder="Title, author, venue or keyword…" autocomplete="off" aria-describedby="publication-count"></div><div class="year-controls" role="group" aria-label="Filter publications by year"><button type="button" data-year-filter="all" aria-pressed="true">All</button>${years.map(year=>`<button type="button" data-year-filter="${year}" aria-pressed="false">${year}</button>`).join('')}</div><button type="button" class="reset-button">Reset filters</button></div><p id="publication-count" class="results-count" aria-live="polite">Showing all ${publications.length} publications</p><div class="publication-list">${publications.map(pub=>publication(pub)).join('\n')}</div><div class="empty-state" hidden><h3>No matching publications.</h3><p>Try a broader keyword or reset the filters.</p><button class="button secondary reset-button" type="button">Reset filters</button></div></div></section>
<section id="highlights" class="section" aria-labelledby="highlights-title"><div class="container"><div class="section-heading"><div><p class="eyebrow">RESEARCH HIGHLIGHTS</p><h2 id="highlights-title">Three threads. One shared goal.</h2></div><p>Making collaborative and intelligent<br>systems more dependable.</p></div><div class="highlights-grid">${data.highlights.map((item,i)=>`<article class="highlight-card ${i===2?'wide':''}"><div class="highlight-cover"><p>${esc(item.label)}</p><span>${esc(item.name)}</span><div class="highlight-tags">${item.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div><div class="highlight-body"><p class="eyebrow">${esc(byId(item.paper).venueShort)} · ${byId(item.paper).year}</p><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p>${external(`https://doi.org/${byId(item.paper).doi}`,'Read the paper','text-link')}</div></article>`).join('')}</div></div></section>
<section id="cv" class="section tint" aria-labelledby="cv-title"><div class="container"><div class="section-heading"><div><p class="eyebrow">CURRICULUM VITAE</p><h2 id="cv-title">Education & experience.</h2></div><div class="cv-actions"><a class="button primary" href="/cv/">View Full CV <span aria-hidden="true">↗</span></a><a class="button secondary" href="/cv/#print">Print / Save as PDF</a></div></div><div class="career-grid">${career('education')}${career('employment')}</div></div></section>
<section id="interests" class="section" aria-labelledby="interests-title"><div class="container"><div class="section-heading"><div><p class="eyebrow">BEYOND RESEARCH</p><h2 id="interests-title">A little more about me.</h2></div><p>Music, mountain trails<br>and the colors of porcelain.</p></div><div class="interests-grid">${data.interests.map(item=>`<article class="interest-card"><img src="/assets/images/${item.image}" alt="${esc(item.alt)}" width="900" height="600" loading="lazy" decoding="async"><div class="interest-body"><p class="eyebrow">${item.category}</p><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p>${tags(item.tags)}</div></article>`).join('')}</div></div></section>
<section id="contact" class="section contact-section" aria-labelledby="contact-title"><div class="container"><div class="contact-heading"><div><p class="eyebrow">CONTACT</p><h2 id="contact-title">Let’s exchange ideas.</h2><p>I welcome conversations about privacy protection, federated learning and secure learning systems.</p></div><a class="button primary" href="mailto:${p.primaryEmail}">Get in touch <span aria-hidden="true">↗</span></a></div><div class="contact-details"><div><span class="contact-label">EMAIL</span><a href="mailto:${p.primaryEmail}">${p.primaryEmail}</a><a class="secondary-email" href="mailto:${p.secondaryEmail}">${p.secondaryEmail}</a></div><div><span class="contact-label">ELSEWHERE</span><div class="inline-links">${external(p.scholarUrl,'Google Scholar')}${external(p.githubUrl,'GitHub')}<a href="/cv/">Curriculum Vitae <span aria-hidden="true">↗</span></a></div></div></div></div></section>
</main>${footer()}</body></html>`;

const cv = `${head(`${p.name} | Curriculum Vitae`,'/cv/','Education, employment and publications of Qingkui Zeng, Lecturer at Tongling University.')}<body class="cv-page" id="home">${header(false)}<main id="main" class="container cv-document"><div class="cv-toolbar" id="print"><a href="/">Back to homepage</a><button class="button primary print-button" type="button" hidden>Print / Save as PDF</button><noscript>Use your browser’s Print command to save this CV as a PDF.</noscript></div><div class="cv-title"><p class="eyebrow">CURRICULUM VITAE</p><h1>${p.name}</h1><p>${p.role} · ${p.school}<br>${p.institution}</p><p class="cv-contact"><a href="mailto:${p.primaryEmail}">${p.primaryEmail}</a><a href="mailto:${p.secondaryEmail}">${p.secondaryEmail}</a></p><div class="inline-links">${external(p.scholarUrl,'Google Scholar')}${external(p.githubUrl,'GitHub')}</div></div><section class="cv-section" aria-labelledby="cv-profile"><h2 id="cv-profile">Research profile</h2><p>Privacy protection and federated learning, with work on local differential privacy, poisoning defenses, efficient edge and IoT learning, and LLM content security.</p></section><section class="cv-section" aria-labelledby="cv-education"><h2 id="cv-education">Education</h2>${data.education.map(item=>`<div class="cv-career"><div><h3>${esc(item.degree)}</h3><p>${esc(item.institution)}</p></div><p>${esc(item.dates)}</p></div>`).join('')}</section><section class="cv-section" aria-labelledby="cv-employment"><h2 id="cv-employment">Employment</h2>${data.employment.map(item=>`<div class="cv-career"><div><h3>${esc(item.role)}, ${esc(item.institution)}</h3><p>${esc(item.school)}</p></div><p>${esc(item.dates)}</p></div>`).join('')}</section><section class="cv-section" aria-labelledby="cv-publications"><h2 id="cv-publications">Publications</h2><p class="muted">${publications.length} papers. Publication years follow the publisher’s final citation.</p><ol class="cv-publications">${publications.map(pub=>publication(pub,true)).join('\n')}</ol></section><section class="cv-section" aria-labelledby="cv-interests"><h2 id="cv-interests">Personal interests</h2><p>Electric guitar and heavy music; hiking; porcelain glaze exploration and kiln firing.</p></section><p class="cv-updated">Updated ${data.updated} · ${p.siteUrl}</p></main>${footer()}</body></html>`;
const notFound = `${head(`Page not found | ${p.name}`,'/404.html','This page could not be found. Return to Qingkui Zeng’s academic homepage.','<meta name="robots" content="noindex">')}<body id="home">${header(false)}<main id="main" class="not-found container"><p class="eyebrow">404 / PAGE NOT FOUND</p><h1>A different path.</h1><p>This page is no longer available. You can find my research, publications and contact details on the homepage.</p><a class="button primary" href="/">Return to homepage</a></main>${footer()}</body></html>`;
await mkdir(path.join(root,'cv'),{recursive:true});
for(const [name,content] of [['index.html',homepage],['cv/index.html',cv],['404.html',notFound]]) await writeFile(path.join(root,name),content+'\n');
await writeFile(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${p.siteUrl}/</loc><lastmod>${data.updated}</lastmod></url><url><loc>${p.siteUrl}/cv/</loc><lastmod>${data.updated}</lastmod></url></urlset>\n`);
await writeFile(path.join(root,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${p.siteUrl}/sitemap.xml\n`);
console.log(`Built homepage, CV, 404 and sitemap with ${publications.length} publications.`);
